In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'name':['John', 'Anna','Peter'],
    'age':[28,34,29],
    'city':['Newyork','Paris','Berlin']
})
df

name  age     city
0   John   28  Newyork
1   Anna   34    Paris
2  Peter   29   Berlin

In [ ]:
df.to_csv('save.csv',index=False)


In [5]:
##Numpy
!pip install numpy

In [6]:
import numpy as np

In [16]:
#Creating arrays
arr = np.array([1,2,3,4,5])
type(arr)

matrix = np.array([[1,2,3],[4,6,7]])
matrix

#using creation functions

# 3*4 array of zeros
np.zeros((3,4))
np.ones((3,4))
np.eye(5) #(5*5 matrix)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
#array attributes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape
arr.ndim
arr.size

dtype('<U11')

In [32]:
#indexing and slicing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr[1,2]  #element at row 1 and column 2
arr[0:2,0:3] # rows 0-1 and columns 0-2
arr[:,1]    # all rows, column 1
arr[1,:]    # row 1, all columns
arr[arr>5] # if elements > 5

array([ 6,  7,  8,  9, 10, 11, 12])

In [59]:
#Reshaping and manipulating arrays

arr = np.arange(12)
arr.shape
reshaped = arr.reshape(3,4)
reshaped.T
reshaped.flatten()


#splitting arrays 
np.split(arr,3)  #splitting into 3 equal parts
np.hsplit(arr,2)
print(reshaped)
np.vsplit(reshaped,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
#mathematical operations
arr1 = np.arange(1,24,2).reshape(3,4)
arr2 = np.arange(1,48,4).reshape(3,4)

print(arr1)
print(arr2)

arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2

np.max(arr1)
np.min(arr1)
np.argmin(arr)
np.argmax(arr)
np.sum(arr)        # sum one by one horizontally
np.sum(arr,axis=0) # sum along column wise

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[ 1  5  9 13]
 [17 21 25 29]
 [33 37 41 45]]


66